// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tazafwvuxdlrngfrvqeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhemFmd3Z1eGRscm5nZnJ2cWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjM0NDQsImV4cCI6MjA1NTE5OTQ0NH0.ihr8hNWqMXlASnXUkFkw0iexCGdU-OYuxMpCQ8H60Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);